project:
  type: website
  output-dir: docs

website:
  title: "Armand Favrot"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: qui suis-je ?
      - href: bibliographie.qmd
        text: Biblio
      - href: cv.qmd
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

